### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by Azaya89** [bokeh/dataviz-fundamentals#20]
Given the renaming of the bar plots file, it has become apparent that regular edits to the table of contents (TOC) will be necessary for each publication on the GH pages to ensure that the links on the Index page correctly point to the corresponding posts.

As a result, this Issue will require ongoing attention throughout the duration of the project.

**Tasks:**
- Confirm that the relevant `.ipynb` and `.html` files have been added to the repository.
- Rewrite, if necessary, the TOC to match the file names
- Add the `.html` file as a link to `Index.html`

**Checklists:**

INTRODUCTION POST
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `Index.html` file

BAR PLOTS
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `Index.html` file

DOT PLOTS AND HEATMAP
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `Index.html` file

SINGLE DISTRIBUTION HISTOGRAM AND DENSITY PLOT
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `index.html` file

MULTIPLE DISTRIBUTION HISTOGRAM AND DENSITY PLOT
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `index.html` file

BOXPLOTS AND RIDGELINE PLOTS
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `index.html` file

SCATTER PLOTS AND CORRELOGRAMS
- [x] Is the topic on the TOC
- [x] Does it have a functional link in the `index.html` file

GEOSPATIAL DATA
- [ ] Is the topic on the TOC
- [ ] Does it have a functional link in the `index.html` file

**Comment by pavithraes** [comment]
Yes, this is a good workflow. We can add notebooks to the TOC as they get published. :)

We do need to update the current README and `index.html` to only have the introduction and visualizaing-amounts-with-bar-plots notebooks

**Comment by Azaya89** [comment]
> We do need to update the current README and `index.html` to only have the introduction and visualizing-amounts-with-bar-plots notebooks

Right. I will create a new branch for this then.
